### PR TITLE
NPM Readiness, Lightweight Readme, etc

### PR DESCRIPTION
**Pull request by DamonOehlman**
Hey Dmitry,

Just started having a look at dr.js and also integrating it into my JS build tool [Interleave](https://github.com/DamonOehlman/interleave).  The doctor is great and I definitely think I'm going to use it for quite a few projects.

I notice that you have published eve into NPM so I think there is definitely an opportunity to do the same with the doctor.  I've added the necessary package.json and also a binary wrapper so people will get a dr-js command line executable if they install the package.  I'm not sure you will be comfortable with adding a dependency on [commander](https://github.com/visionmedia/commander.js) but I've found it pretty useful when writing node.js command line tools.

Additionally, I've added a README which I'll happily keep adding to as I find the time and get more familiar dr.js.

Finally, I made a few modifications to the main dr.js file so integration with both the binary wrapper and interleave were a little more seamless.  I'm sure the code is far from perfect, but I think it may help with dr.js adoption.

Thanks again for taking the time to write dr.js :)

Cheers,
Damon.

### CODE REVIEW

**Comment by DmitryBaranovskiy** [comment]
npm is totally fucked on my computers. I assume I did something wrong while installing node, so I am not using npm. I pushed my latest changes to dr.js, so your pull can’t be merged easily now.

As you can note, I added raphael.json as an example of configuration json instead of command line parameters.

**Comment by DamonOehlman** [comment]
I saw the changes go up - I'll see if I can do something on my side to merge it all together...

With regards to npm it would be awesome if things like dr.js and eve (latest version) were there.  Happy to publish versions that you are happy with on your behalf while npm is busted on your machine, if you like...

**Comment by DmitryBaranovskiy** [comment]
Please publish them if you can. Thanks.

**Comment by DamonOehlman** [comment]
Published: http://search.npmjs.org/#/dr-js

Also merged your new updates across.  Adjusted the way that I modified `dr.js` too so that you can still use it (depending on whether `module.parent` is defined it either exports the main function or executes it on the ARGV parameters).

Another change I made was to remove the additional line breaks added in the console logging.  This was a little selfish but makes the output much nicer to read when interleave spits out the dr.js output...

**Comment by chikamichi** [comment]
+1 for the README :)

**Comment by DamonOehlman** [comment]
No longer relevant.

**Pull request closed without merging**
